apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
  namespace: mongo-express
data:
  ME_CONFIG_MONGODB_URL: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-service.mongo-db.svc.cluster.local:27017/"